#ifndef PINS_H
#define PINS_H

#include "io.h"

#define DECLARE_PIN(var)  \
extern IOPin pin_##var;   \

DECLARE_PIN(EXT_CPU_EN);
DECLARE_PIN(EXT_RESETB);
DECLARE_PIN(EXT_CLK_EN);
DECLARE_PIN(DEV_TBO);
DECLARE_PIN(VBP);
DECLARE_PIN(SYNC);
DECLARE_PIN(MLB);
DECLARE_PIN(EXT_CLK);
DECLARE_PIN(DEV_ENB);
DECLARE_PIN(RWB);
DECLARE_PIN(NMIB);
DECLARE_PIN(IRQB);

DECLARE_PIN(DATA_0);
DECLARE_PIN(DATA_1);
DECLARE_PIN(DATA_2);
DECLARE_PIN(DATA_3);
DECLARE_PIN(DATA_4);
DECLARE_PIN(DATA_5);
DECLARE_PIN(DATA_6);
DECLARE_PIN(DATA_7);

DECLARE_PIN(ADDR_00);
DECLARE_PIN(ADDR_01);
DECLARE_PIN(ADDR_02);
DECLARE_PIN(ADDR_03);
DECLARE_PIN(ADDR_04);
DECLARE_PIN(ADDR_05);
DECLARE_PIN(ADDR_06);
DECLARE_PIN(ADDR_07);

DECLARE_PIN(ADDR_08);
DECLARE_PIN(ADDR_09);
DECLARE_PIN(ADDR_10);
DECLARE_PIN(ADDR_11);
DECLARE_PIN(ADDR_12);
DECLARE_PIN(ADDR_13);
DECLARE_PIN(ADDR_14);
DECLARE_PIN(ADDR_15);

typedef enum {
  PinId_EXT_CPU_EN = 1,
  PinId_EXT_RESETB = 2,
  PinId_EXT_CLK_EN = 4,
  PinId_DEV_TBO = 21,
  PinId_VBP = 23,
  PinId_SYNC = 25,
  PinId_MLB = 29,
  PinId_EXT_CLK = 31,
  PinId_DEV_ENB = 33,
  PinId_RWB = 35,
  PinId_NMIB = 37,
  PinId_IRQB = 39,

  PinId_DATA_0 = 3,
  PinId_DATA_1 = 5,
  PinId_DATA_2 = 7,
  PinId_DATA_3 = 9,
  PinId_DATA_4 = 13,
  PinId_DATA_5 = 15,
  PinId_DATA_6 = 17,
  PinId_DATA_7 = 19,

  PinId_ADDR_00 = 8,
  PinId_ADDR_01 = 10,
  PinId_ADDR_02 = 12,
  PinId_ADDR_03 = 14,
  PinId_ADDR_04 = 16,
  PinId_ADDR_05 = 18,
  PinId_ADDR_06 = 20,
  PinId_ADDR_07 = 22,

  PinId_ADDR_08 = 26,
  PinId_ADDR_09 = 28,
  PinId_ADDR_10 = 30,
  PinId_ADDR_11 = 32,
  PinId_ADDR_12 = 34,
  PinId_ADDR_13 = 36,
  PinId_ADDR_14 = 38,
  PinId_ADDR_15 = 40
} PinId;

#endif

