#include "pins.h"
#include <avr/io.h>

#define DEFINE_PIN(VAR, CTX_ID) \
IOPin pin_##VAR = {             \
  .name = #VAR,                 \
  .id = PinId_##VAR,            \
  .ctx_id = CTX_ID,             \
  .mode = iom_UNKNOWN,          \
  .state = io_UNKNOWN           \
};                              \

DEFINE_PIN(EXT_CPU_EN, 1);
DEFINE_PIN(EXT_RESETB, 2);
DEFINE_PIN(EXT_CLK_EN, 4);
DEFINE_PIN(DEV_TBO, 21);
DEFINE_PIN(VBP, 23);
DEFINE_PIN(SYNC, 25);
DEFINE_PIN(MLB, 29);
DEFINE_PIN(EXT_CLK, 31);
DEFINE_PIN(DEV_ENB, 33);
DEFINE_PIN(RWB, 35);
DEFINE_PIN(NMIB, 37);
DEFINE_PIN(IRQB, 39);

DEFINE_PIN(DATA_0, PD4);
DEFINE_PIN(DATA_1, PD5);
DEFINE_PIN(DATA_2, PD6);
DEFINE_PIN(DATA_3, PD7);
DEFINE_PIN(DATA_4, PB0);
DEFINE_PIN(DATA_5, PB1);
DEFINE_PIN(DATA_6, PB2);
DEFINE_PIN(DATA_7, PB3);

DEFINE_PIN(ADDR_00, 8);
DEFINE_PIN(ADDR_01, 10);
DEFINE_PIN(ADDR_02, 12);
DEFINE_PIN(ADDR_03, 14);
DEFINE_PIN(ADDR_04, 16);
DEFINE_PIN(ADDR_05, 18);
DEFINE_PIN(ADDR_06, 20);
DEFINE_PIN(ADDR_07, 22);

DEFINE_PIN(ADDR_08, 26);
DEFINE_PIN(ADDR_09, 28);
DEFINE_PIN(ADDR_10, 30);
DEFINE_PIN(ADDR_11, 32);
DEFINE_PIN(ADDR_12, 34);
DEFINE_PIN(ADDR_13, 36);
DEFINE_PIN(ADDR_14, 38);
DEFINE_PIN(ADDR_15, 40);

